version: '3'
services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    restart: always
    depends_on:
      - server
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_tHl4kPQj9pKa@ep-shy-rain-abtjgbsv-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always